services:
  fastapi-app:
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "20002:20002"
    volumes:
      - ./src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 20002 --reload --workers 4
